### ISSUE TITLE
which blog engine is that ?

### ISSUE THREAD

**Issue by darkworks** [ricardo/ricardo.github.io#1]
Hi
hope you doing well.
i came across your blog : https://ricardometring.com/
its very nice and clean  may i know you custom made it or is it using any open source blog engine , will be thankful if you could share info as looking for nice and clean blog engine as am bit tired of wordpress its heavy 

thanks

**Comment by ricardo** [comment]
Hi, I made it from scratch using Laravel. The posts are written in Markdown and then formatted to HTML using https://github.com/GrahamCampbell/Laravel-Markdown.

Hope you find this information useful.

Cheers.

**Comment by darkworks** [comment]
> Hi, I made it from scratch using Laravel. The posts are written in Markdown and then formatted to HTML using https://github.com/GrahamCampbell/Laravel-Markdown.
> 
> Hope you find this information useful.
> 
> Cheers.

currently there is no simple clean blog open source engine out there , so do you have anyplan to open source the engine or make put small price tag on it on codecanyon where people can buy it.
the hasnode https://hashnode.com/  is quite clean lovely engine but not open source also no adsense etc monetization support. i wish there could have one out there

thanks

**Comment by ricardo** [comment]
I have no plans to open source it, as that wouldn't be an easy endeavor.
