### ISSUE TITLE
Autoselect option depending on input's value

### ISSUE THREAD

**Issue by Parvares** [ricardo/ricardo.github.io#2]
Hi Ricardo, I read [your article](https://ricardometring.com/getting-the-value-of-a-select-in-javascript), could I ask you a question?
From this saved static page:

https://spazioweb.w3spaces.com/reference.html

I would like would be autoselected:

"INTERNA" in "Circolazione" dropdown field, if

user writes "REF." in "Sezione"

Thanks for your assistance!

**Comment by ricardo** [comment]
Hi @Parvares, sorry, I can't provide 1:1 support.

If you want something to happen based on an input value, you should add an event listener to that input. E.g:

```javascript
document.getElementById('cdSezi').addEventListener('change', (ev) => {
    const val = ev.target.value;
    if (val === 'REF.') {
        // Select circolazione.
        document.getElementById('idtpCircolazione').value = 'I';
    }
});
```

Didn't test the above code, but I hope it helps you in the right direction.

**Comment by Parvares** [comment]
Thank you very much, Ricardo, it works!
